---
- hosts: all
  vars:
    db_user: dspace
    db_name: dspace
    db_password: dspace
  tasks:
   - name: Install dependencies for PostgreSQL
     apt: name={{ item }} update_cache=true state=latest
     with_items:
     - bash
     - openssl
     - libssl-dev
     - libssl-doc

   - name: Install PostgreSQL 
     apt: name={{ item }} update_cache=true state=present
     with_items:
     - postgresql
     - postgresql-contrib
     - libpq-dev
     - python3-psycopg2

   - name: Ensure the PostgreSQL service is running
     service: name=postgresql state=started enabled=yes 
    
   - name: Create the database specified in vars
     become: true
     become_user: postgres
     postgresql_db: name={{ db_name }}
          template='template0'
          state=present

   - name: Ensure user has access to the new database
     become: true
     become_user: postgres
     postgresql_user: 
          db={{ db_name }}
          name={{ db_user }}
          password={{ db_password }}
          state=present

   - name: Ensure user does not have unnecessary permissions
     become: true
     become_user: postgres
     postgresql_user: name={{ db_user }}
          role_attr_flags=NOSUPERUSER,NOCREATEDB
          state=present 

   - name: GRANT ALL PRIVILEGES ON DATABASE dspace TO dspace
     community.postgresql.postgresql_privs:
          db={{ db_name }}
          privs=ALL
          type=database
          role={{ db_user }}

  handlers:
    - name: restart postgres
      service: name=postgresql state=restarted
